django_test/django_test/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
	path('polls/', include('polls.urls')),
]

django_test/polls/urls.py
from django.urls import path

from . import views

# https://bitsofpy.blogspot.com/2009/07/matplotlib-in-django.html
#   from django.conf.urls.defaults import *

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    # detail(request=<HttpRequest object>, question_id=34)
    path('details/<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),


    # path('<int:question_id>/vote/', views.vote_on_choice, name='choice_vote')
    path('<int:question_id>/graph_results', views.graph_results, name='graph_results')
]

django_test/polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
    	return self.question_text

    def was_publiched_recently(self):
    	return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
    	return self.choice_text

# Create your models here.

django_test/polls/views.py
# from django.shortcuts import render

from django.http import HttpResponse, HttpResponseRedirect
# from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.urls import reverse

from .models import Question, Choice

def index(request):
    print("polls haduken")
    print(request)
    # questions = Question.objects.all()
    # texto = ", ".join([str(q) for q in questions])
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    output = ', '.join([q.question_text for q in latest_question_list])

    # template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    # return HttpResponse(output)
    # return HttpResponse(template.render(context, request))
    return render(request, 'polls/index.html', context)

# Create your views here.

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist as dne:
        raise Http404("Question does not exist. Questão não existe")
    return render(request, 'polls/detail.html', {'question': question})
    # return HttpResponse("You're looking at question %s." % question_id)

def results(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist as dne:
        # raise Http404("Questão não existe {}".format(dne.message()))
        raise Http404("Questão não existe {}".format(dne))
    # response = "You're looking at the results of question: %s."
    return render(request, 'polls/results.html', {'question': question})
    # return HttpResponse(response % question)
    # return HttpResponse(response % question_id)

def vote(request, question_id):
    print("votaaaar")
    question = get_object_or_404(Question, pk=question_id)
    print(question)
    try:
        # question = Question.objects.get(pk=question_id)
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay de question voting form.
        return render(request, 'polls/detail.html', {
            'question': question, 
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

# def vote_on_choice(request, question_id, choice):
#     print("votando vote_on_choice" % choice)
#     return HttpResponse("You're voting for choice {} on question {}.".format(choice, question_id))

def graph_results(request, question_id):
	print("executando graph_results")
	import matplotlib
	from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
	from matplotlib.figure import Figure
	from matplotlib.dates import DateFormatter
	fig = Figure()

	ax = fig.add_subplot(1,1,1)
	question = get_object_or_404(Question, pk=question_id) # Get the question object
	
	x = matplotlib.numpy.arange(1, question.choice_set.count())
	choices = question.choice_set.all()

	votes = [choice.votes for choice in choices]
	names = [choice.choice_text for choice in choices]

	numTests = question.choice_set.count()
	ind = matplotlib.numpy.arange(numTests) # the x locations for the groups

	cols = ['red', 'orange', 'yellow', 'green', 'blue', 'purple', 'indigo']*10

	cols = cols[0:len(ind)]
	ax.bar(ind, votes, color=cols)

	ax.set_xticks(ind + 0.5)
	ax.set_xticklabels(names)

	ax.set_xlabel("Choices")
	ax.set_ylabel("Votes")

	ax.grid(True)

	title = "Dynamically Generated Results Plot \nfor question: %s" % question.question_text
	ax.set_title(title)

	canvas = FigureCanvas(fig)

	# from django import settings
	from django.conf import settings
	# print("importado")
	# print(type(settings.BASE_DIR))
	# print(settings.BASE_DIR)

	# import os
	# img_path = os.path.join(settings.BASE_DIR, '/polls/static/polls/images/')
	img_path = settings.BASE_DIR + '/polls/static/polls/images/'
	# img_path.join('/polls/static/polls/images/')
	img_path += 'question{}.png'.format(question.id)

	# print("img_path ", img_path)
	# from . import urls
	# print("app_name ", app_name)

	# get app name
	# from apps import PollsConfig
	# print(PollsConfig.name)

	fig.savefig(img_path) # salva a figura   savefig('foo.png', bbox_inches='tight')

	# sleep(5)

	# https://docs.python.org/3/library/io.html
	# from io import BytesIO
	# bio = BytesIO()
	# canvas.print_png(bio)
	# plot = bio.getvalue()
	# return HttpResponse(plot, content_type='image/png')


	# return render(request, 'polls/results.html', {'question': question, 'plot', plot})
	return render(request, 'polls/results.html', {'question': question,})

django_test/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
		<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
	{% endfor %}
	<input type="submit" name="Vote" />
</form>

<!-- <ul> -->
	<!-- {% for choice in question.choice_set.all %} -->
		<!-- <li>{{ choice.choice_text }}</li> -->
	<!-- {% endfor %} -->
<!-- </ul> -->

<a href="{% url 'polls:index' %}">Voltar</a>

django_test/polls/templates/polls/grafico_pub_function.html
<!DOCTYPE html>
<html>
<head>
	<title>meu teste</title>
</head>
<body>

</body>

<script type="text/javascript" src="//pubnub.github.io/eon/v/eon/1.0.0/eon.js"></script>
<link type="text/css" rel="stylesheet" href="//pubnub.github.io/eon/v/eon/1.0.0/eon.css"/>
<div id="gauge"></div>
<script type="text/javascript">
var pubnub_gauge = new PubNub({
  publishKey: "pub-c-3ef4941c-5a95-497a-b7bf-ed6d0823b186",
  subscribeKey: "sub-c-cd8b8d8e-6941-11e8-98cb-067913ebee63"
});
gauge_chart = eon.chart({
  pubnub: pubnub,
  channels: ["dados_cisterna"],
  history: true,
  generate: {
    bindto: '#gauge',
    data: {
      type: 'gauge',
    },
    // distancia: {
    // 	type: "gauge",
    // }
    gauge: {
      min: 0,
      max: 100
    },
    color: {
      pattern: ['#FF0000', '#F6C600', '#60B044'],
      threshold: {
        values: [30, 60, 90]
      }
    }
  }
});
</script>


<script type="text/javascript" src="https://pubnub.github.io/eon/v/eon/1.0.0/eon.js"></script>
<link type="text/css" rel="stylesheet" href="https://pubnub.github.io/eon/v/eon/1.0.0/eon.css" />
<div id="chart"></div>
<script type="text/javascript">
var __eon_pubnub = new PubNub({
  subscribeKey: "sub-c-cd8b8d8e-6941-11e8-98cb-067913ebee63"
});
var __eon_cols = ["distancia"]; 
var __eon_labels = {}; 
chart = eon.chart({
  pubnub: __eon_pubnub,
  channels: ["dados_cisterna"],
  history: true,
  flow: true,
  rate: 1000,
  limit: 5,
  generate: {
    bindto: "#chart",
    data: {
      colors: {"tempo":"#D70060","distancia":"#E54028"},
      type: "spline"
    },
    transition: {
      duration: 250
    },
    axis: {
      x: {
        label: "tempo"
      },
      y: {
        label: "distância"
      }
    },
    grid: {
      x: {
        show: true 
      },
      y: {
        show: true 
      }
    },
    tooltip: {
     show: true
    },
    point: {
      show: true
    }
  },
  transform: function(message) {
    var message = eon.c.flatten(message.eon);
    var o = {};
    for(index in message) {
      if(__eon_cols.indexOf(index) > -1){
        o[__eon_labels[index] || index] = message[index];
      }
    }
    return {
      eon: o
    };
  }
});
</script>


<!-- <script type="text/javascript" src="https://pubnub.github.io/eon/v/eon/1.0.0/eon.js"></script>
<link type="text/css" rel="stylesheet" href="https://pubnub.github.io/eon/v/eon/1.0.0/eon.css" />
<div id="chart"></div>
<script type="text/javascript">
var __eon_pubnub = new PubNub({
  subscribeKey: "sub-c-bd9ab0d6-6e02-11e5-8d3b-0619f8945a4f"
});
var __eon_cols = ["Austin","Portland"]; 
var __eon_labels = {}; 
chart = eon.chart({
  pubnub: __eon_pubnub,
  channels: ["test-channel-0.6569502841791012"],
  history: true,
  flow: true,
  rate: 1000,
  limit: 5,
  generate: {
    bindto: "#chart",
    data: {
      colors: {"Austin":"#D70060","New York":"#E54028","San Francisco":"#F18D05","Portland":"#113F8C"},
      type: "spline"
    },
    transition: {
      duration: 250
    },
    axis: {
      x: {
        label: "label_eixo_x"
      },
      y: {
        label: "label_eixo_y"
      }
    },
    grid: {
      x: {
        show: true 
      },
      y: {
        show: true 
      }
    },
    tooltip: {
     show: true
    },
    point: {
      show: true
    }
  },
  transform: function(message) {
    var message = eon.c.flatten(message.eon);
    var o = {};
    for(index in message) {
      if(__eon_cols.indexOf(index) > -1){
        o[__eon_labels[index] || index] = message[index];
      }
    }
    return {
      eon: o
    };
  }
});
</script> -->



</html>

django_test/polls/templates/polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style/style.css' %}" />
<head>
	<!-- fav icon não esqueça load static antes -->
	<link rel="shortcut icon" href="{% static '/polls/hlusp_ico.ico' %}">
</head>

{% if latest_question_list %}
    <ul>
	<table>
		<tr>
			<td>ID da questão</td>
			<td>Questão</td>
			<td>Data de publicação</td>
			<td>Votar</td>
			<td>Resultados</td>
		</tr>
	    {% for question in latest_question_list %}
	    	<tr>
	    		<td>{{ question.id }}</td>
	    		<td><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></td>
	    		<td>{{ question.pub_date }}</td>
	    		<td><a href="{% url 'polls:vote' question.id %}">Votar</a></td>
		    	<td><a href="{% url 'polls:results' question.id %}">Resultados</a></td>
		    	<td><a href="{% url 'polls:graph_results' question.id %}">Resultados em gráficos</a></td>
	    	</tr>
			
		    <!-- <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li> -->
		    <!-- </li> -->
    	{% endfor %}
	</table>
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<img src="/static/polls/images/figura2.png" width="500px">

django_test/polls/templates/polls/results.html
{% load static %}
<head>
	<!-- fav icon não esqueça load static antes -->
	<link rel="shortcut icon" href="{% static '/polls/hlusp_ico.ico' %}">
</head>

<h1>{{ question.question_text }}</h1>

<ul>
	{% for choice in question.choice_set.all %}
	<li>
		{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}
	</li>
	{% endfor %}
</ul>
<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

<!-- <img src="{% static 'polls/figura.png' %}" alt="My image"/> -->

<img src="{% static 'polls/images/question' %}{{question.id}}.png" alt="My image"/>